--会員テーブル
CREATE TABLE IF NOT EXISTS users (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255) NOT NULL, 
   age INT NOT NULL,
   email VARCHAR(255) NOT NULL,  
   password VARCHAR(255) NOT NULL,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

--愛鳥テーブル
CREATE TABLE IF NOT EXISTS birds (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL, 
    name VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(50) NOT NULL,
    birthday VARCHAR(50) NOT NULL,
    best_weight INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,    
    FOREIGN KEY (user_id) REFERENCES users (id)
);

--健康記録テーブル
CREATE TABLE IF NOT EXISTS health_records (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bird_id INT NOT NULL, 
    day DATE NOT NULL,
    weight INT NOT NULL,
    meal_amount INT NOT NULL,
    temperature INT NOT NULL,
    humidity INT NOT NULL,
    memo VARCHAR(255) NOT NULL, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,    
    FOREIGN KEY (bird_id) REFERENCES birds (id)
);